---
name: "Install git-metrics"
description: "This action will download the git-metrics binary from github and install it on the current runner."
branding:
  icon: activity
  color: white
inputs:
  version:
    description: "Expected version of git-metrics"
    required: false
    default: "latest"
runs:
  using: composite
  steps:
    - name: list files
      shell: bash
      run: ls -lha ${{ github.action_path }}

    - name: making script executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh

    - name: executing script
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        GH_TOKEN: ${{ github.token }}
