name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  version:
    description: 'git-metrics version'
    default: 'v0.1.2'

# Define your outputs here.
outputs:
  already-installed:
    description: 'Wether git-metrics was already installed'

runs:
  using: node20
  main: dist/index.js
