name: testing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-on-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - name: execute git-metrics
        run: git-metrics --help
      - name: execute git metrics
        run: git metrics --help
