name: testing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-on-macos-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - name: execute git-metrics
        run: git-metrics --help

  run-on-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - name: execute git-metrics
        run: git-metrics --help
