name: testing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  running:
    strategy:
      fail-fast: true
      matrix:
        platform: ['macos-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdrouet/action-install-git-metrics@main
      - name: execute git-metrics
        run: git-metrics --help
